# Generated by Django 3.0.6 on 2020-06-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_one',
            field=models.TextField(null=True),
        ),
    ]
